# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis
# and https://github.com/eddelbuettel/r-travis/
#
# See README.md for instructions.

language: c

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  # get two locally built packages / backports of current QuantLib
  - curl -OL http://dirk.eddelbuettel.com/code/ubuntu/12.04/amd64/libquantlib0.deb
  - curl -OL http://dirk.eddelbuettel.com/code/ubuntu/12.04/amd64/libquantlib0-dev.deb

install:
  - ./travis-tool.sh install_aptget r-cran-runit r-cran-rgl r-cran-zoo
  - ./travis-tool.sh install_r Rcpp
  - dpkg -i libquantlib0.deb libquantlib-dev.deb

script: 
  - ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

    

